#!/bin/sh
# createindex.sh creates index.html, an index of all icons
#
# Copyright (C) 1998, 2018 Jürgen Reuter
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

date=`date` ; export date
cat > index.html <<EOF

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
  <!-- ######## WARNING: This file is automatically created.  ######## -->
  <!-- ######## Do not edit this file manually, since all     ######## -->
  <!-- ######## manual changes will be lost upon next update. ######## -->
  <!-- Automatically created on: $date -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>SysExEdit: Icons for General-Purpose Use</title>
  </head>
  <body>
    <h2>SysExEdit: Icons for General-Purpose Use</h2>
    <table>
      <thead>
        <tr>
          <th>Icon</th>
          <th>Property Name</th>
          <th>File Path</th>
        </tr>
      </thead>
      <tbody>
EOF
icons_props=`grep -e "^[^#]*=" ../icons.properties`
for icon_props in $icons_props ; do (
    icon_id=`echo $icon_props | cut -d"=" -f1`
    icon_abs_path=`echo $icon_props | cut -d"=" -f2`
    icon_rel_path=`echo $icon_abs_path | sed -e "s/^\/icons\///g"`
cat >> index.html <<EOF
        <tr>
          <td>
            <a href="$icon_rel_path">
              <img src="$icon_rel_path" alt="$icon_id" border="0" />
            </a>
          </td>
          <td>
            $icon_id
          </td>
          <td>
            <a href="$icon_rel_path">$icon_abs_path</a>
          </td>
        </tr>
EOF
) ; done
cat >> index.html <<EOF
      </tbody>
    </table>
  </body>
</html>
EOF

#  Local Variables:
#    coding:utf-8
#    mode:sh
#  End:
